# Generated by Django 5.2.4 on 2025-07-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
