# Generated by Django 5.2.4 on 2025-08-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debateapp', '0002_alter_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('human', 'Human'), ('ai', 'AI')], default='human', max_length=20),
        ),
    ]
